name: "JFrog Integration Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout
        uses: actions/checkout@v3
         
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:  
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: env
        run: env           
      - name: Run Docker command
        run: docker run --rm --mount type=bind,source="$(pwd)",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
